apiVersion: v1
kind: Service
metadata:
  labels:
    name: history
  name: history
  namespace: dojot
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: history
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: history
  name: history
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: history
    spec:
      containers:
      - image: dojot/history:latest
        name: history
        env:
        - name: FALCON_SETTINGS_MODULE
          value: history.settings.docker
        - name: REPLICA_SET
          value: rs0
        - name: KAFKA_HOST
          value: kafka-server:9092
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: persister
  name: persister
  namespace: dojot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: persister
    spec:
      containers:
      - image: dojot/persister:latest
        name: persister
        env:
        - name: FALCON_SETTINGS_MODULE
          value: history.settings.docker
        - name: REPLICA_SET
          value: rs0
        - name: KAFKA_HOST
          value: kafka-server:9092
      restartPolicy: Always
