apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
  namespace: dojot
  labels:
    names: postgres
spec:
  serviceName: postgres-cluster
  replicas: 3
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
    spec:
      serviceAccountName: postgres
      containers:
      - name: spilo
        image: registry.opensource.zalan.do/acid/spilo-9.6:1.2-p17
        env:
        # TODO: Set all this passwords as secrets
        - name: PGPASSWORD_SUPERUSER
          value: kong
        - name: PGPASSWORD_ADMIN
          value: kong
        - name: PGPASSWORD_STANDBY
          value: kong
        - name: ZOOKEEPER_HOSTS
          value: zk-server
        - name: SCOPE
          value: postgres
        - name: USE_WALE
          value: ""
        - name: POD_NAMESPACE
          value: dojot
        ports:
        - containerPort: 8008
        - containerPort: 5432
        volumeMounts:
        - name: postgres-volume
          mountPath: "/home/postgres/pgdata/pgroot"
          subPath: ""
  volumeClaimTemplates:
    - metadata:
        name: postgres-volume
        namespace: dojot
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
